mutation CreateComment($issueId: String!, $body: String!) {
  commentCreate(input: { issueId: $issueId, body: $body }) {
    success
    comment {
      id
      body
      createdAt
      user {
        id
        name
      }
      issue {
        id
        identifier
        title
      }
    }
  }
}
