query GetSubIssues($id: ID!) {
  issues(
    filter: {
      parent: { id: { eq: $id } }
      state: { name: { nin: ["Canceled", "Done", "Duplicate"] } }
    }
    first: 250
  ) {
    nodes {
      identifier
      title
      description
      priorityLabel
      subIssueSortOrder
      state {
        name
      }
      comments(first: 250) {
        nodes {
          body
          createdAt
          updatedAt
        }
      }
      inverseRelations(first: 50) {
        nodes {
          type
          issue {
            identifier
            title
            state {
              name
            }
          }
        }
      }
      relations(first: 50) {
        nodes {
          type
          relatedIssue {
            identifier
            title
            state {
              name
            }
          }
        }
      }
      labels {
        nodes {
          name
          parent {
            name
          }
        }
      }
      children(
        filter: { state: { name: { nin: ["Canceled", "Done", "Duplicate"] } } }
        first: 50
      ) {
        nodes {
          identifier
          title
          description
          priorityLabel
          subIssueSortOrder
          state {
            name
          }
          comments(first: 250) {
            nodes {
              body
              createdAt
              updatedAt
            }
          }
          inverseRelations(first: 50) {
            nodes {
              type
              issue {
                identifier
                title
                state {
                  name
                }
              }
            }
          }
          relations(first: 50) {
            nodes {
              type
              relatedIssue {
                identifier
                title
                state {
                  name
                }
              }
            }
          }
          labels {
            nodes {
              name
              parent {
                name
              }
            }
          }
          children(
            filter: { state: { name: { nin: ["Canceled", "Done", "Duplicate"] } } }
            first: 1
          ) {
            nodes {
              identifier
            }
          }
        }
      }
    }
  }
}
