query GetSubIssueStatuses($id: ID!) {
  issue(id: $id) {
    identifier
    title
    comments(first: 250) {
      nodes {
        body
        createdAt
        updatedAt
      }
    }
  }
  issues(
    filter: {
      parent: { id: { eq: $id } }
      state: { name: { nin: ["Canceled", "Duplicate"] } }
    }
    first: 250
  ) {
    nodes {
      identifier
      title
      description
      subIssueSortOrder
      state {
        name
        type
      }
      comments(first: 250) {
        nodes {
          body
          createdAt
          updatedAt
        }
      }
      inverseRelations(first: 50) {
        nodes {
          type
          issue {
            identifier
            title
            state {
              name
              type
            }
          }
        }
      }
      children(
        filter: { state: { name: { nin: ["Canceled", "Duplicate"] } } }
        first: 250
      ) {
        nodes {
          identifier
          title
          description
          subIssueSortOrder
          state {
            name
            type
          }
          comments(first: 250) {
            nodes {
              body
              createdAt
              updatedAt
            }
          }
          inverseRelations(first: 50) {
            nodes {
              type
              issue {
                identifier
                title
                state {
                  name
                  type
                }
              }
            }
          }
        }
      }
    }
  }
}
