query GetSubIssues($id: ID!) {
  issues(
    filter: {
      parent: { id: { eq: $id } }
      state: { name: { nin: ["Canceled", "Done", "Duplicate"] } }
    }
    first: 250
  ) {
    nodes {
      identifier
      title
      priorityLabel
      subIssueSortOrder
      state {
        name
      }
      labels {
        nodes {
          name
          parent {
            name
          }
        }
      }
      children(
        filter: { state: { name: { nin: ["Canceled", "Duplicate"] } } }
        first: 50
      ) {
        nodes {
          identifier
          title
          priorityLabel
          subIssueSortOrder
          state {
            name
          }
          labels {
            nodes {
              name
              parent {
                name
              }
            }
          }
        }
      }
    }
  }
}
